# Introdução à Ciência de Dados - UFPB
Professor: Yuri Malheiros

## NumPy

Implemente a função `distance` abaixo. Ela deve receber dois pontos e retornar a distância euclidiana entre eles. Cada ponto é representado por um array do NumPy, por exemplo, `p1 = np.array([2,4])` representa o ponto com coordenadas x=2 e y=2.

In [ ]:
import numpy as np

def distance(p1, p2):
    """
    >>> distance(np.array([0,0]), np.array([1,1]))
    1.4142135623730951
    
    >>> distance(np.array([1,2]), np.array([3,4]))
    2.8284271247461903
    
    >>> distance(np.array([5,2]), np.array([-2,-1]))
    7.615773105863909
    """
    
    return ((p1[0]-p2[0])**2 + (p1[1]-p2[1])**2) ** (1/2)

Implemente a função `n_distances` abaixo. Ela recebe um ponto (`p1`), como um array do NumPy, e uma lista de pontos (`points`), uma matriz do NumPy, onde cada linha representa um ponto.

Esta função deve retornar a distância de `p1` para todos os pontos da matriz `points`. O retorno também é uma matriz, onde cada linha tem a distância de `p1` para o ponto daquela linha.

In [ ]:
def n_distances(p1, points):
    """
    >>> n_distances(np.array([0,0]), np.array([[1,1]]))
    array([1.41421356])
    
    >>> n_distances(np.array([0,0]), np.array([[1,1], [2,2]]))
    array([1.41421356, 2.82842712])
    
    >>> n_distances(np.array([1,2]), np.array([[3,-1], [2,1], [5, 2], [10, 1], [-2, -5]]))
    array([3.60555128, 1.41421356, 4.        , 9.05538514, 7.61577311])
    """
    
    # ADICIONE O SEU CÓDIGO AQUI
    # no final do notebook foi colocado mais 3 variações desta função com teste de velocidade
    matriz = np.zeros(points.shape[0])
    i=0
    for p in points:
        matriz[i] = distance(p1,p)
        i+=1
    return matriz

## Teste

In [ ]:
import doctest

doctest.testmod(verbose=True)


PYDEV DEBUGGER WARNING:
sys.settrace() should not be used when the debugger is being used.
This may cause the debugger to stop working correctly.
If this is needed, please check: 
http://pydev.blogspot.com/2007/06/why-cant-pydev-debugger-work-with.html
to see how to restore the debug tracing back correctly.
Call Location:
  File "/usr/lib/python3.7/doctest.py", line 1487, in run
    sys.settrace(save_trace)



Trying:
    distance(np.array([0,0]), np.array([1,1]))
Expecting:
    1.4142135623730951
ok
Trying:
    distance(np.array([1,2]), np.array([3,4]))
Expecting:
    2.8284271247461903
ok
Trying:
    distance(np.array([5,2]), np.array([-2,-1]))
Expecting:
    7.615773105863909
ok
Trying:
    n_distances(np.array([0,0]), np.array([[1,1]]))
Expecting:
    array([1.41421356])
ok
Trying:
    n_distances(np.array([0,0]), np.array([[1,1], [2,2]]))
Expecting:
    array([1.41421356, 2.82842712])
ok
Trying:
    n_distances(np.array([1,2]), np.array([[3,-1], [2,1], [5, 2], [10, 1], [-2, -5]]))
Expecting:
    array([3.60555128, 1.41421356, 4.        , 9.05538514, 7.61577311])
ok
5 items had no tests:
    __main__
    __main__.n_distances1
    __main__.n_distances2
    __main__.n_distances3
    __main__.n_distances4
2 items passed all tests:
   3 tests in __main__.distance
   3 tests in __main__.n_distances
6 tests in 7 items.
6 passed and 0 failed.
Test passed.


TestResults(failed=0, attempted=6)

# Teste de velocidade de variações da função n_distances

In [ ]:
def n_distances1(p1, points):
    matriz = np.array([])
    for p in points:
        d = np.array([distance(p1,p)])
        matriz = np.concatenate( (matriz, d) )  
    return matriz

def n_distances2(p1, points):
    matriz = np.zeros(points.shape[0])
    i=0
    for p in points:
        matriz[i] = distance(p1,p)
        i+=1
    return matriz

def n_distances3(p1, points): 
    matriz = []
    for p in points:
        matriz.append(distance(p1,p))
    matriz = np.array(matriz)
    return matriz

def n_distances4(p1, points): 
    return np.array([distance(p1,p) for p in points ])



In [ ]:
p1, points = np.array([1,2]), np.array([[3,-1], [2,1], [5, 2], [10, 1], [-2, -5]])

In [ ]:
%time n_distances1(p1, points) # criando np.array vazio e preencher com concatenate

CPU times: user 1.17 ms, sys: 33 µs, total: 1.2 ms
Wall time: 5.17 ms


array([3.60555128, 1.41421356, 4.        , 9.05538514, 7.61577311])

In [ ]:
%time n_distances2(p1, points) # criand array com np.zeros e substituindo valores

CPU times: user 81 µs, sys: 17 µs, total: 98 µs
Wall time: 102 µs


array([3.60555128, 1.41421356, 4.        , 9.05538514, 7.61577311])

In [ ]:
%time n_distances3(p1, points) # preenchendo lista com for e transformando no final em np.array

CPU times: user 107 µs, sys: 23 µs, total: 130 µs
Wall time: 135 µs


array([3.60555128, 1.41421356, 4.        , 9.05538514, 7.61577311])

In [ ]:
%time n_distances4(p1, points) # usando list comprehension

CPU times: user 100 µs, sys: 21 µs, total: 121 µs
Wall time: 124 µs


array([3.60555128, 1.41421356, 4.        , 9.05538514, 7.61577311])